system = [
  "gamemode",       # Game mode utility
  "input-remapper", # Remap inputs from peripherals | https://github.com/sezanzeb/input-remapper
  "openal-soft",    # Headphone virtual surround support
]

flatpak = [
  "com.bitwarden.desktop",            # Password manager | https://bitwarden.com/
  "com.usebottles.bottles",           # Wine GUI | https://usebottles.com/
  "com.github.finefindus.eyedropper", # Color picker | https://github.com/FineFindus/eyedropper
  "com.fastmail.Fastmail",            # Fastmail client | https://www.fastmail.com/
  "com.github.tchx84.Flatseal",       # Flatpak permissions | https://github.com/tchx84/Flatseal
  "it.mijorus.gearlever",             # AppImage manager | https://github.com/mijorus/gearlever
  "org.kde.krita",                    # Art! | https://krita.org/en/
  "io.github.screwys.Rufin",          # Music library | https://github.com/screwys/Rufin
  "dev.vencord.Vesktop",              # Modified Discord client | https://github.com/Vencord/Vesktop
  "com.visualstudio.code",            # One day nvim will be good for debugging | https://code.visualstudio.com/
  "app.drey.Warp",                    # Like portal, but GUI | https://apps.gnome.org/Warp/
  "io.github.zen_browser.zen",        # Custom Firefox layer | https://zen-browser.app/
]

gearlever = [
  { name = "Filen", url = "https://cdn.filen.io/@filen/desktop/release/latest/Filen_linux_x86_64.AppImage" },
  { name = "Obsidian", url = "https://github.com/obsidianmd/obsidian-releases/releases/latest/download/Obsidian-1.13.7.AppImage" },
  { name = "Neovide", url = "https://github.com/neovide/neovide/releases/latest/download/neovide.AppImage" },
  { name = "Vial", url = "https://github.com/vial-kb/vial-gui/releases/latest/download/Vial-v0.7.5-x86_64.AppImage" },
  { name = "Wezterm", url = "https://github.com/wezterm/wezterm/releases/download/nightly/WezTerm-nightly-Ubuntu24.04.AppImage" },
  { name = "ZMK Studio", url = "https://github.com/zmkfirmware/zmk-studio/releases/latest/download/ZMK.Studio_0.3.1_amd64.AppImage" },
]

cargo = [
  "systemctl-tui", # Systemd viewer | https://github.com/rgwood/systemctl-tui
]
