force_links = true

[[create]]
dir = "~/Applications"
mode = 0o755

[[create]]
dir = "~/Downloads"
mode = 0o755

[[create]]
dir = "~/Projects"
mode = 0o755

clean = [
  "~",
  { dir = "~/.config", recursive = true },
  { dir = "~/.tmux", recursive = true },
]


[links]
"~" = "linked/home/*"
"~/.config" = "linked/.config/*"
"~/.tmux/plugins/tpm" = "linked/tmux/tpm"
"~/.config/tmux/tmux.conf" = "linked/tmux/tmux.conf"

[[hooks.before.deploy]]
name = "Sync git submodules"
command = "git submodule update --init --recursive"

[[hooks.before.deploy]]
name = "Sync uv"
command = "uv sync"

[[hooks.before.deploy]]
name = "Install dots as global tool"
command = "uv tool install --editable --force ."

[[hooks.after.link]]
name = "Install Iosevka nerd font"
command = "scripts/install-iosevka"
mode = "silent"

[[hooks.before.install]]
name = "Install NVM"
command = "bash -c \"$(curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh)\""

[[hooks.before.install]]
name = "Install latest LTS node & npm"
command = "bash -lc 'nvm install --lts && nvm alias default \"lts/*\"'"

[[hooks.before.install]]
stage = "flatpak"
name = "Ensure flathub added to flatpak"
command = "command -v flatpak >/dev/null && flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"

[[hooks.after.install]]
name = "Fix fd access"
command = "command -v fd &> /dev/null || { mkdir -p ~/.local/bin && ln -sf $(which fdfind) ~/.local/bin/fd; }"
mode = "silent"

[[hooks.after.install]]
name = "Update TLDR cache"
command = "tldr --update"

[[hooks.after.install]]
name = "Prepare Neovim"
command = "nvim --headless '+Lazy! sync' +qa"

[[hooks.after.deploy]]
name = "Set up github known host"
command = "./scripts/setup/git"
mode = "interactive"

[[hooks.after.deploy]]
name = "Ensure github cli auth"
command = "gh auth status || gh auth login"
mode = "interactive"
