#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

# Plugins
OMNIPKGPLUGIN="${BASEDIR}/dotbot-plugins/dotbot-omnipkg/omnipkg.py"
INCLUDEPLUGIN="${BASEDIR}/dotbot-plugins/dotbot-include/include.py"
CONDITIONALPLUGIN="${BASEDIR}/dotbot-plugins/dotbot-conditional"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "$BASEDIR" \
    -c "$CONFIG" \
    -p "$OMNIPKGPLUGIN" \
    -p "$INCLUDEPLUGIN" \
    --plugin-dir "$CONDITIONALPLUGIN" \
    "${@}"
