#!/usr/bin/env bash

set -e

CONFIGS=(
    "dotbot-configs/management.yaml"
    "dotbot-configs/software.yaml"
    "dotbot-configs/desktop.yaml"
    "dotbot-configs/niri.yaml"
    "dotbot-configs/themes.yaml"
)
DEFAULTS="defaults.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

for CONFIG in "${CONFIGS[@]}"; do
    echo "Executing config $CONFIG..."
    TEMPFILE=$(mktemp)
    cat "$DEFAULTS" > "$TEMPFILE"
    tail -n +2 "$CONFIG" >> "$TEMPFILE"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
        -d "$BASEDIR" \
        -c "$TEMPFILE" \
        "${@}" || continue
done

echo "Finished executing configs."
