system = [

  # Languages / build support
  "clang",             # C frontend for LLVM
  "cmake",             # Why is this not on be default
  "luarocks",          # Lua package manager | https://luarocks.org/
  "python3",           # Python 3.x | https://www.python.org/
  "python3-fontforge", # Fontforge support
  "python-is-python3", # Python -> python3. 2 is old.
  "python3-pip",       # Ensure pip3
  "python3-venv",      # Virtualenv support

  [ # pkg-config — openssl-sys etc. use it to locate libs
    "pkg-config",
    "pkgconf",
  ],
  [ # Go | https://go.dev/
    "go",
    "golang",
  ],
  [ # Ensure dev support
    "python3-dev",
    "python3-devel",
  ],

  # System apps
  "unzip",         # .zip support
  "zsh",           # Z Shell | https://www.zsh.org/
  "inotify-tools", # inotify utilities | https://github.com/inotify-tools/inotify-tools
  "alacritty",     # Terminal emulator | https://github.com/alacritty/alacritty
  "ghostty",       # Terminal emulator | https://github.com/ghostty-org/ghostty

  [ # 7zip support
    "7zip",
    "p7zip",
    "p7zip-full",
    "7-zip",
  ],
  [
    "7zip-rar",
    "p7zip-rar",
  ],
  "p7zip-plugins",

  # System dependencies
  "chafa",                      # Terminal graphics support | https://github.com/hpjansson/chafa
  "gstreamer1-plugin-openh264", # Ensure video support on linux
  "mozilla-openh264",           # Ensure video support in firefox on linux
  "ttfautohint",                # More font building support | https://freetype.org/ttfautohint/
  "xclip",                      # Ensure nvim clipboard works in wayland
  "clutter-gtk",                # Ensure gnome addon TopHat works
  "socat",                      # Bidirectional socket relay
  "rocm-smi",                   # GPU interface library? Used by btop
  { macos = "coreutils" },      # Ensure coreutils on MacOS
  "file",                       # Used by yazi for filetype ID
  "ffmpeg",                     # Used by yazi for thumbnailing
  "resvg",                      # Used by yazi for SVG rendering
  "zoxide",                     # Used by yazi for history jumping
  "curl",                       # Still surprised curl is left out of some systems
  "exiftool",                   # Media metadata info

  [ # Image manipulation library, used by yazi
    "imagemagick-full",
    "imagemagick",
    "ImageMagick",
  ],
  [ # PDF rendering library, used by yazi
    "poppler",
    "poppler-utils",
  ],
  [ # Ensure full font support on linux
    "font-noto",
    "google-noto-sans-*",
  ],
  [ # OpenSSL dev headers
    "libssl-dev",
    "openssl-devel",
    "libopenssl-devel",
    "openssl",
  ],

  # Utilities
  "ffmpegthumbnailer", # Video/Audio thumbnailer | https://github.com/dirkvdb/ffmpegthumbnailer
  "figlet",            # Big text | http://www.figlet.org/
  "fontforge",         # Font builder | https://github.com/fontforge/fontforge
  "git-delta",         # Pager/file comparison | https://github.com/dandavison/delta
  "lolcat",            # Colorful text | https://github.com/busyloop/lolcat
  "yank",              # Terminal output -> Clipboard | https://github.com/mptre/yank
  "sd",                # Sane sed | https://github.com/chmln/sd

  [ # Faster/friendlier find | https://github.com/sharkdp/fd
    "fd",
    "fd-find",
  ],


]

brew = [

  # Data tools
  "csvlens",        # less for CSV/TSV | https://github.com/YS-L/csvlens
  "fx",             # TUI JSON/YAML viewer | https://github.com/antonmedv/fx
  "jless",          # TUI JSON viewer | https://github.com/PaulJuliusMartinez/jless
  "jq",             # CLI JSON transformer | https://github.com/jqlang/jq
  "jqp",            # TUI for JQ | https://github.com/noahgorstein/jqp
  "kiki-ki/tap/qo", # Query JSON/CSV/TSV with SQL | https://github.com/kiki-ki/go-qo
  "tidy-viewer",    # Quick CSV+ pretty-printer | https://github.com/alexhallam/tv

  # Dependencies
  "openssl", # Pyenv compatibility with linuxbrew
  "tcl-tk",  # Python tkinter support

  # Editors
  "nvim", # Modal editor | https://github.com/neovim/neovim

  # Fetches
  "cpufetch", # CPU information | https://github.com/Dr-Noob/cpufetch
  "hyfetch",  # Neofetch with Pride | https://github.com/hykilpikonna/hyfetch
  "onefetch", # Git repo info | https://github.com/o2sh/onefetch
  "macchina", # Super fast fetch in rust | https://github.com/Macchina-CLI/macchina

  # File management
  "dua-cli",           # TUI disk usage analyzer | https://github.com/Byron/dua-cli
  "lf",                # Lightweight TUI file manager | https://github.com/gokcehan/lf
  "umlx5h/tap/gtrash", # Integrated TUI trash manager | https://github.com/umlx5h/gtrash
  "walk",              # inline TUI file manager | https://github.com/antonmedv/walk
  "yazi",              # Fast featureful file manager | https://github.com/sxyazi/yazi

  # Fluff
  "clainstone/tap/cbirds", # Boids | https://github.com/clainstone/cbirds
  "cbonsai",               # Bonsai tree generator | https://github.com/mhzawadi/homebrew-cbonsai
  "cmatrix",               # Matrix animation | https://github.com/abishekvashok/cmatrix
  "phlx0/drift/drift",     # Screensavers | https://github.com/phlx0/drift

  # Git
  "gh",                            # GitHub CLI | https://cli.github.com/
  "jesseduffield/lazygit/lazygit", # TUI git manager | https://github.com/jesseduffield/lazygit

  # Package/language management
  "eget", # Github prebuilt binary installer | https://github.com/zyedidia/eget
  "pnpm", # Performant NPM | https://github.com/pnpm/pnpm

  # Utilities
  "bat",                  # Better cat/less | https://github.com/sharkdp/bat
  "btop",                 # Better top | https://github.com/aristocratos/btop
  "ccat",                 # Colorful cat | https://github.com/owenthereal/ccat
  "cloc",                 # LOC counter | https://github.com/AlDanial/cloc
  "ctpv",                 # File previewer | https://github.com/NikitaIvanovV/ctpv
  "entr",                 # Run commands on file change | https://github.com/eradman/entr
  "fzf",                  # TUI Fuzzy finder | https://github.com/junegunn/fzf
  "glow",                 # Terminal Markdown Renderer | https://github.com/charmbracelet/glow
  "jump",                 # Smart cd'ing | https://github.com/gsamokovarov/jump
  "lazydocker",           # TUI Docker management | https://github.com/jesseduffield/lazydocker
  "lsd",                  # Deluxe ls | https://github.com/lsd-rs/lsd
  "nap",                  # TUI snippet manager | https://github.com/maaslalani/nap
  "navi",                 # FZF Cheatsheet | https://github.com/denisidoro/navi
  "nvtop",                # Like top for GPUs | https://github.com/syllo/nvtop
  "portal",               # Internet file transfer | https://github.com/SpatiumPortae/portal
  "ripgrep",              # Recursive grep | https://github.com/BurntSushi/ripgrep
  "ast-grep",             # Structural grep & replace | https://github.com/ast-grep/ast-grep
  "tmux",                 # Terminal multiplexer | https://github.com/tmux/tmux
  "xh",                   # Friendlier cURL | https://github.com/ducaale/xh
  "gum",                  # Shell script utility | https://github.com/charmbracelet/gum
  "kew",                  # TUI Music library and player | https://codeberg.org/ravachol/kew
  "brevity1swos/tap/rgx", # TUI Regex tester | https://github.com/brevity1swos/rgx
  "SurgeDM/tap/surge",    # Fast download manager | https://github.com/surgedm/surge
]

cargo = [
  "cargo-update", # For updating cargo packages
  "tealdeer",     # faster tldr
  "tabiew",       # tsv viewer
  "shellharden",  # shell formatter / fixer
  "taplo-cli",    # TOML formatter/linter (binary: taplo) | https://taplo.tamasfe.dev
  "purple-ssh",   # SSH config manager and container viewer | https://github.com/erickochen/purple
]

uv = [

  # System support
  "pylatexenc", # LaTeX parser
  "pynvim",     # Extended nvim support

  # Tools
  "asciinema", # Record terminal interactions
  "yq",        # like jq but with yaml+toml
  "posting",   # API client | https://github.com/darrenburns/posting
]

pnpm = [
  "npm",    # For nvim mason
  "neovim", # Neovim support
]

gh-ext = [
  "mintarchit/gh-contribs", # Contribution graph
  "sheepla/gh-userfetch",   # User info fetch
  "dlvhdr/gh-dash",         # Github dash
]
