#!/bin/bash
shopt -s expand_aliases
cd "${0%/*}" # execute from script dir
# TODO add something to make the first python on path point to the venv interpreter
# cleanup on exit or fail
exithandler() {
    rm -rf iosevka_setup_env || true
}
trap exithandler ERR EXIT

fontgen() {
    # handle creation in a virtual environment
    python3 -m venv iosevka_setup_env --clear
    alias python='./iosevka_setup_env/bin/python3'
    alias pip='./iosevka_setup_env/bin/pip3'

    pip install -r iosevka-generate/requirements.txt
    python iosevka-generate/iosevka-generate
    mv ~/.local/share/fonts/tokebe* ./cached
}

linkfonts() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        ln -sf ./cached ~/.local/share/fonts/iosevka-tokebe
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        ln -sf ./cached ~/Library/Fonts/iosevka-tokebe
    fi
}

source ../scripts/yesno
if yesno 'Re-generate custom Iosevka nerd font?' $?
then
    echo "Generating Font..."
    fontgen
    linkfonts
else
    echo 'Skipping font generation (copy cached font files)...'
    linkfonts
    exit
fi
