#!/bin/bash
shopt -s expand_aliases
cwd="$(realpath ./"${0%/*}")"
cd $cwd # execute from script dir
# TODO add something to make the first python on path point to the venv interpreter
# cleanup on exit or fail
exithandler() {
    rm -rf iosevka_setup_env || true
}
trap exithandler ERR EXIT

fontgen() {
    # handle creation in a virtual environment
    python3 -m venv iosevka_setup_env --clear
    # alias python='./iosevka_setup_env/bin/python3'
    # alias pip='./iosevka_setup_env/bin/pip3'

    ./iosevka_setup_env/bin/pip3 install -r iosevka-generate/requirements.txt
    ./iosevka_setup_env/bin/python3 iosevka-generate/iosevka-generate
    mv ~/.local/share/fonts/Tokebe* ./cached
}

linkfonts() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # ensure link goes as desired
        if [ ! -d ~/.local/share/fonts ]; then
            mkdir -p ~/.local/share/fonts
        fi
        unlink ~/.local/share/fonts/iosevka-tokebe &> /dev/null
        rm -rf ~/.local/share/fonts/iosevka-tokebe &> /dev/null
        ln -sf "$cwd/cached" ~/.local/share/fonts/iosevka-tokebe
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        cp -a "$cwd/cached/." ~/Library/Fonts
    fi
}

source ../scripts/yesno
if yesno 'Re-generate custom Iosevka nerd font?' $?
then
    echo "Generating Font..."
    fontgen
    linkfonts
else
    echo 'Skipping font generation (copy cached font files)...'
    linkfonts
    exit
fi
