theme = "rose-pine-moon"
padding-x = 0
padding-y = [10, 10]

[fonts]
family = "tokebe"
features = ["dlig"]
# >=
size = 20

[window]
opacity = 1
blur = true
decorations = "disabled"

[renderer]
target-fps = 100

[navigation]
clickable = true
