#!/usr/bin/env bash

setup () {
    local cwd=$PWD
    cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    mkdir -p config
    cp -f ./neofetch-themes/normal/config.conf config/config.conf

    cd "$cwd"
}
setup
