#!/usr/bin/env bash
setup () {
    local cwd=$PWD
    cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit

    # systemctl --user add-wants niri.service swww-bg.service
    # systemctl --user add-wants niri.service swww-overview.service
    # systemctl --user add-wants niri.service swww-cycle.service
    # systemctl --user add-wants niri.service ignis.service
    systemctl --user add-wants niri.service swayidle.service
    systemctl --user add-wants niri.service mate-polkit.service

    # Get the latest Noctalia
    mkdir -p ~/.config/quickshell/noctalia-shell && curl -sL https://github.com/noctalia-dev/noctalia-shell/releases/latest/download/noctalia-latest.tar.gz | tar -xz --strip-components=1 -C ~/.config/quickshell/noctalia-shell

    # Set gtk theme so Noctalia can customize it
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'

    source ../get_distro
    get_distro

    # Install quickshell on Fedora
    if [[ $OS == *Fedora* ]]; then
        sudo dnf -y copr enable errornointernet/quickshell
        sudo dnf -y install --refresh quickshell
    fi

    cd "$cwd" || exit
}
setup
