#!/usr/bin/env bash
setup () {
    local cwd=$PWD
    cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit

    echo "Installing UV tools..."
    while IFS="" read -r tool || [ "$tool" != "" ]
    do
      uv tool install --upgrade "$tool"
    done < ../../uv-tools.txt

    cd "$cwd" || exit
}
setup
