#!/usr/bin/env bash

# Set the path to the wallpapers directory
wallpapersDir="$HOME/OneDrive/wallpaper/desktop-alter"

# Get a list of all image files in the wallpapers directory
wallpapers=("$wallpapersDir"/*)

# Start an infinite loop
while true; do
    # Check if the wallpapers array is empty
    if [ ${#wallpapers[@]} -eq 0 ]; then
        # If the array is empty, refill it with the image files
        wallpapers=("$wallpapersDir"/*)
    fi

    # Select a random wallpaper from the array
    wallpaperIndex=$(( RANDOM % ${#wallpapers[@]} ))
    selectedWallpaper="${wallpapers[$wallpaperIndex]}"

    # Update the wallpaper using the swww img command
    # Any = circle centered at any point
    swww img "$selectedWallpaper" --transition-type any --transition-fps 100 --transition-duration 2

    # Remove the selected wallpaper from the array
    wallpapers=("${wallpapers[@]}")

    # Delay for 10 minutes before selecting the next wallpaper
    sleep 10m
done
