[profile]
priority = 5
when = { os = "linux" }

[[hooks.before.install]]
name = "Add terra"
command = "command -v dnf && dnf repolist installed terra-release >/dev/null 2&>1 || sudo dnf install --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release"
