#!/usr/bin/env bash

package_updates=$(dnf check-upgrade --refresh -q | grep -c '^[a-z0-9]')
brew_updates=$(brew upgrade -n | sed -nE 's/.*([0-9]+) outdated packages:/\1/p')
flatpak_updates=$(yes no | flatpak update | grep -e '^\s*[0-9+]\.' | tail -1 | sed -nE 's/^\s([0-9]+)\..+/\1/p')

# shellcheck source=./vars
source "$(dirname "${BASH_SOURCE[0]}")/vars"

noctalia_current_tag=$(cd "$shell_dir" && git describe --exact-match --tags)
noctalia_latest_tag=$(curl -sL -m 15 --connect-timeout 5 https://api.github.com/repos/"$shell_repo"/releases/latest | grep 'tag_name' | sed -E 's/.*"([^"]+)".*/\1/' || echo "$noctalia_current_tag")
noctalia_updates=0; [ "$noctalia_current_tag" != "$noctalia_latest_tag" ] && noctalia_updates=1


echo "$((package_updates+brew_updates+flatpak_updates+noctalia_updates))"
