#!/usr/bin/env bash

# shellcheck source=./vars
source "$(dirname "${BASH_SOURCE[0]}")/vars"

latest_release_tag=$(curl -sL -m 10 --connect-timeout 5 https://api.github.com/repos/"$shell_repo"/releases/latest | grep 'tag_name' | sed -E 's/.*"([^"]+)".*/\1/')

rm -rf "$shell_dir"

git clone \
  --depth 1 \
  --branch="$latest_release_tag" \
  "https://github.com/noctalia-dev/noctalia-shell.git" \
  "$shell_dir"
