#!/usr/bin/env bash

# shellcheck source=./vars
source "$(dirname "${BASH_SOURCE[0]}")/vars"

latest_release_tag=$(curl -sL -m 10 --connect-timeout 5 https://api.github.com/repos/"$shell_repo"/releases/latest | grep 'tag_name' | sed -E 's/.*"([^"]+)".*/\1/')

cd "$shell_dir" || exit
git fetch --tags
git checkout "tags/$latest_release_tag"
