[mgr]
prepend_keymap = [
    { on = "\\", run = "plugin split-tabs spl_toggle", desc = "Split-tabs: toggle split tabs mode" },
    { on = "<Tab>", run = "plugin split-tabs spl_switch_tab", desc = "Split-tabs: switch to the other pane" },
    { on = "<F5>", run = [ "escape --visual", "plugin split-tabs spl_copy" ], desc = "Split-tabs: copy to the other pane" },
    { on = "<F6>", run = [ "escape --visual", "plugin split-tabs spl_move" ], desc = "Split-tabs: move to the other pane" },
    { on = "P", run = "plugin split-tabs spl_preview", desc = "Split-tabs: toggle preview pane" },
    { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on  = "M", run = "plugin mount", desc = "Manage mounts" },
    { on = "F", run = "plugin smart-filter", desc = "Smart filter", },
    { on = [ "c", "m" ], run  = "plugin chmod", desc = "Chmod on selected files" },
    { on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
    { on = "<C-p>", run = "shell --orphan -- sushi '%s'" }
]
