#!/usr/bin/env bash
yesno() {
    while true; do
        # echo "$1 (y/n) "
        read -p "$1 (y/n) " yn
        case $yn in
            [Yy]* ) return 0 ;;
            [Nn]* ) return 1 ;;
            * ) echo "Please answer yes or no." ;;
        esac
    done
}
