#!/usr/bin/env bash
setup () {
    local cwd=$PWD
    cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source ../scripts/yesno

    if yesno 'Install ZSH for Humans?' $?
    then
        echo "ZSH for Humans will be installed."
        echo "It will be installed and an interactive prompt will help you configure it."
        echo
        echo "After setup completes, use exit to resume the dotfile install script."
        echo "(ZSH for Humans opens a new zsh instance and I can't stop it)"
        sleep 5s
        echo
        echo "------------------------------------------------------------------------------"
        echo
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"
    else
        echo "Skipping ZSH for Humans installation."
    fi
    cd "$cwd"
}
setup
